# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c81ececf807e926514fa366fd7b62118c7e6ab0252bbf7afd72e95daf029fa61c2b27228e8ffaadd3e9227fb0ff85ed36ba81e6437ddf1019ba72133baabbf06

test:
  secret_key_base: a817efbb06ea734151730d1246dec17ada960c4c3f386a3590f882c3bda976d6edc0fc7bb2bb10eeef173efe5d2414858747fc8385327c9880073a2e92aa76df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
